version: 2

defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: node:10.13.0
  environment:
    - NODE_ENV: "development"

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/workspace
          paths:
              - .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: run unit tests
          command: npm test
      - store_artifacts:
          path: CIRCLE_TEST_REPORTS/jest
      - store_test_results:
          path: CIRCLE_TEST_REPORTS/jest
  linter:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: run eslint
          command: npm run lint:ci -- --format junit --output-file CIRCLE_TEST_REPORTS/eslint/result.xml
      - store_artifacts:
          path: CIRCLE_TEST_REPORTS/eslint
      - store_test_results:
          path: CIRCLE_TEST_REPORTS/eslint
workflows:
  version: 2
  build:
    jobs:
      - install
      - test:
          requires:
            - install
      - linter:
          requires:
            - install
